# Hydrolab Data

*Hydrolab data not published. For more details and for access to hydrolab data from this site contact Kenai Watershed Forum at [hydrology\@kenaiwatershed.org](mailto:hydrology@kenaiwatershed.org) or call the office at (907) 262-5449.*

To assess variation in water quality throughout time, two OTT Hydrolab MS5 multiparameter water quality sondes ("Hydrolabs") were deployed at the inlet of Miller Creek where it exits Vogel Lake in summer 2021 and summer 2022. The pair of Hydrolabs were placed in the center of the stream midway through the water column suspended from a buoy. Prior to deployment, all Hydrolabs were calibrated in accordance with the Department of Environmental Conservation (DEC)-approved Quality Assurance Project Plan: Kenai River Watershed Monitoring Program requirements ([KWF, 2019](https://paperpile.com/app/p/7703451b-460d-00b4-82a0-1086ea2554c3)). Post-retrieval, Hydrolabs underwent quality assurance checks for all parameters assessed in the field. Prior to departure, quality control measures were taken to ensure proper data collection including cleaning of Hydrolabs and ensuring the use of calibration solutions prior to expiration dates.

Hydrolab data were assessed in Fall 2022. Parameters included temperature, pH, dissolved oxygen, conductivity, turbidity, and temperature. Results were found to be of mixed reliability for characterizing water quality at this site. Due to the site's remote location and the low flow rate in Miller Creek, the schedule necessary to maintain the hydrolabs (probe cleaning, battery replacement, calibration) was not maintained on a schedule that would be standard practice at a road accessible site. As a result, hydrolab data at this site is not published in this report. Some parameters (e.g. temperature) yielded more consistently reliable data than others that employed probes which may have seen some algae growth (e.g. turbidity). For more details and for access to hydrolab data from this site, contact Kenai Watershed Forum at [hydrology\@kenaiwatershed.org](mailto:hydrology@kenaiwatershed.org){.email} or call their office at (907) 262-5449.
